[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm run start:prod"
healthcheckPath = "/health/ready"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "backend"

[services.variables]
NODE_ENV = "production"
PORT = "3001"
CORS_ORIGIN = "http://localhost:3000,https://ecommerce-hack-rnpu.vercel.app,https://ecommerce-hack-rnpu-4njuh8tlx-sebast219s-projects.vercel.app,https://*.vercel.app"
